### ISSUE TITLE
Discover new Lists

### ISSUE THREAD

**Issue by Osahashi** [krisu5/userstyles#3]
Twitter always know how to fucked up everything, the new "feature" is:

![discover new lists](https://user-images.githubusercontent.com/22057956/105981645-9a98d400-6096-11eb-96ce-c8529c758686.JPG)

I'm using lists for users I don't follow and some stuff, the made the same on the Android app. You can pin a few lists on top and swipe like a second timeline, for the app it's okay, but on the web that's not possible, it makes no sense to pin a list on Twitter web. 

Would be really nice if you could remove it with next update.

**Comment by krisu5** [comment]
I'm kinda conflicted about this. I personally don't mind the "Discover New Lists" _for now_, because it only shows three lists and it's not in the main / user timelines (at least I haven't seen one yet). Also, I kinda like suggestions what Twitter has offered for lists at least for me, but I understand that it could be annoying to some.

I guess best compromise for my personal usage is to [bookmark "Suggested Lists" page](https://twitter.com/i/lists/suggested) and block the section because of my "philosophy". (I don't want to disable specific rules in my end because of [dogfooding](https://en.wikipedia.org/wiki/Eating_your_own_dog_food))

**Comment by Osahashi** [comment]
I understand what you mean. Suggestions can be helpful to find something new, but in 99% they are pretty annoying and the worst thing is, there is no setting to turn them off, Twitter force it and doesn't give use the possibility to turn suggestions off.

Maybe write the URL to the suggested lists page in the readme/notes for other users.

**Comment by krisu5** [comment]
I added the blocks related to this. Update your filterlists.

There might be some weird animation effects when uBlock blocks the elements, that I can't control.
